scrape_configs:
  - job_name: 'Spring Boot Application input'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:8081']
        labels:
          application: 'My Spring Boot Application'

  - job_name: 'TOLS Sprint Boot App'
    metrics_path: '/tols-services/actuator/prometheus'
    scrape_interval: 5s
    basic_auth:
        username: 'user'
        password: ''
    static_configs:
      - targets: ['tols-perf-1.gt.t-kartor.se']
        labels:
          application: 'TOLS Services'
